--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackMD/MysteryCrate
branches:
- master
projects:
  MysteryCrate:
    path: ""
    lint:
      phpstan: false
    icon: meta/MysteryCrate.png
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^1.0.0
      - src: muqsit/InvMenu/InvMenu
        version: ^2.0.0
      - src: JackMD/ConfigUpdater/ConfigUpdater
        version: ^1.0.0
...
